# Use the official Ubuntu base image
FROM ubuntu:latest

# Update the APT package repository
RUN apt-get update

# Upgrade currently installed software without prompting
RUN apt-get upgrade -y

# Set the default command to echo "Hello, World!"
CMD echo "Hello, World!"
